### ISSUE TITLE
Is there a bug in model_transformer.py ?

### ISSUE THREAD

**Issue by xdjwolf** [ZijianD/Brain-TokenGT#1]
In my experiment， when I debug to: 
_out = self.transformer_encoder(all_embeddings).mean(0)_  in model_transformer.py, 

I got this error: 
tgt_len, bsz, embed_dim = query.size()
ValueError: not enough values to unpack (expected 3, got 2),

I thought the input for self.transformer_encoder must be 3 dimensions, but actually, it was  2 dimensions.

**Comment by yilei-wu** [comment]
Thank you for your interest, the input for self.transformer_encoder is supposed to be in 2D. It should be in the shape of [batch_size * num_node/tp, embedding].

**Comment by ZijianD** [comment]
Thank you for your interest! Now the input of self.transformer_encoder is 2D, the first dimension is the number of tokens for one trajectory, the second dimension is embedding. Now we can only "batch" on tokens instead of participant. We will try to imrpove it and welcome to contribute!
